apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod-demo
spec:
  containers:
  - image: httpd:latest
    imagePullPolicy: IfNotPresent
    name: liveness-container
    command: ['sh', '-c', 'echo liveness Container is Running ; sleep 30']
    ports:
    - name: liveness-port
      containerPort: 80
      hostPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 2
      periodSeconds: 10
      failureThreshold: 2
  restartPolicy: Always

  